name: Sync FTP Data

on:
  schedule:
    # Run once a day at midnight
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync_ftp_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: Sync FTP files
        run: |
          lftp -e "
            mirror --verbose --continue --parallel=10 --dereference ftp://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/sumstats_harm_status/Harm_sumstats_status.db sumstats_fastapi/Data/ 
            quit
          "

      - name: Commit synced data
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Sync FTP data"
          git push
